#!/opt/homebrew/bin/bash

((!$#)) && echo No commit message, command ignored! && exit 1

cMessage="$1"

eval declare -A percents=(
	"$(github-linguist | awk '/%[[:space:]]/ { gsub(/CSS/,"cssPercent",$3); gsub(/HTML/,"htmlPercent",$3); gsub(/JavaScript/,"jsPercent",$3); printf "[\"%s\"]=\"%s\"\n", $3, $1 }')"
)

# echo "$(github-linguist | awk '/%[[:space:]]/ { gsub(/CSS/,"cssPercent",$3); gsub(/HTML/,"htmlPercent",$3); gsub(/JavaScript/,"jsPercent",$3); printf "[\"%s\"]=\"%s\"\n", $3, $1 }')";


while IFS=' ' read line; do for i in "${!percents[@]}"; do \
    line="${line//"$i"/"${percents["$i"]}"}"; done; echo "$line"; done <stats_template.html > stats.html

gsed -i "s/curTime/$(date '+%a %d %b %H:%M:%S')/g" stats.html

echo "git add ."
echo "$(git add .)"
echo "git commit -m \"$cMessage\""
echo "$(git commit -m "$cMessage")"

unset percents
