#!/bin/bash

# ((!$#)) && echo No commit message, command ignored! && exit 1


# declare -A percents
# echo "$(github-linguist | awk '/%[[:space:]]/ { gsub(/CSS/,"cssPercent",$2); gsub(/HTML/,"htmlPercent",$2); gsub(/JavaScript/,"jsPercent",$2); print $2 " " $1 }')" | awk '/[[:space:]]/ {gsub(/$1/,$2)}' sedReplace
# echo "$(github-linguist | awk '/%[[:space:]]/ { gsub(/CSS/,"cssPercent",$2); gsub(/HTML/,"htmlPercent",$2); gsub(/JavaScript/,"jsPercent",$2); percents[$2]=$1 }')"
eval declare -A percents=(
	"$(github-linguist | awk '/%[[:space:]]/ { gsub(/CSS/,"cssPercent",$2); gsub(/HTML/,"htmlPercent",$2); gsub(/JavaScript/,"jsPercent",$2); printf "[\"%s\"]=\"%s\"\n", $2, $1 }')"
)

# awk '/[[:space:]]/ {gsub(/jsPercent/,)}' sedReplace
while IFS=' ' read line; do for i in "${!percents[@]}"; do \
    line="${line//"$i"/"${percents["$i"]}"}"; done; echo "$line"; done <stats_template.html > stats.html


# eval declare -A USERARRAY=(
    # $(awk -F: '{ printf "[\"%s\"]=\"%s\"\n", $2, $1}' )
# )

# echo "${percents[@]}"
# for i in "${!percents[@]}"
# do
#   echo "key  : $i"
#   echo "value: ${percents[$i]}"
# done

# unset percents



git add .
# git commit -m $1